### ISSUE TITLE
Humano ultrapassando as bordas

### ISSUE THREAD

**Issue by aronsales** [aronsales/RobotsGUIDO-ARON#1]
Problema nos limites do mapa, o humano está ''saindo'' do mapa quando o jogador seleciona, o que não era pra estar acontecendo.

**Comment by guidoferrario** [comment]
É verdade! Estou trabalhando no sentido de impedir que exista um comando na direção dos limites do tabuleiro quando o usuário já estivar próximo de tal localização.

**Comment by aronsales** [comment]
Quando o problema for resolvido fecho este issue.

**Comment by guidoferrario** [comment]
Problema corrigido! 
#closed
