### ISSUE TITLE
Comandos invertidos

### ISSUE THREAD

**Issue by guidoferrario** [aronsales/RobotsGUIDO-ARON#2]
Durante testes do programa constatei que quando o usuário pressiona as teclas com o objetivo de executar alguma das possíveis ações, o "personagem" do jogo dá uma resposta trocada. Isto é, quando tenta ir para cima, vai para uma casa a esquerda etc. 

Também precisamos adicionar os lixos.

**Comment by aronsales** [comment]
Acho que já tenho uma resposta para este problema, irei incrementar e coloco no programa.
Assim que o problema estiver resolvido eu fecho este issue.

**Comment by guidoferrario** [comment]
Problema corrigido. 
#closed
